server:
  port: 31001
spring:
  application:
    name: springboot-linux
  freemarker:
    cache: false #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
  datasource:
    username: root
    password: root
    url: jdbc:mysql://101.132.128.127:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 101.132.128.127
    port: 6379
    password:
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: 300ms
        max-idle: 8
        min-idle: 4


mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

logging:
  level:
    com:
      z:
        dao : debug